name: Check
on: [ push, pull_request]
jobs:
  tests:
    name: nix flake check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.NIX_SECRETS }}

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          install_url: "https://nixos.org/nix/install"

      - name: Get metadata
        run: nix flake metadata

      - name: Show outputs
        run: nix flake show --all-systems

      - name: Check flake
        run: nix flake check --all-systems .?submodules=1#
